### ISSUE TITLE
Criar variáveis CSS com os padrões do projeto

### ISSUE THREAD

**Issue by laviodias** [ic045-sistemaacademico-2023/frontend-sistema-academico-ic-ufba#3]
Definir algumas constantes como cores, espaçamentos, tamanhos de fonte, tipos de fonte, estilização de inputs, etc.

Docs do tailwind sobre o assunto: https://tailwindcss.com/docs/configuration

**Comment by MatheusCCarmo** [comment]
estou tocando essa
